### ISSUE TITLE
polyfill-ed list

### ISSUE THREAD

**Issue by azu** [nicjansma/usertiming.js#15]
Hi, Thanks for nice library.
I want to know that what is method/property polyfill-ed by usertiming.js.

I notice that some property is not polyfilled like `window.performance.timing.responseStart`.
Is there any way to know polyfill-ed method/property list?

**Comment by nicjansma** [comment]
Hi @azu.  usertiming.js polyfills support for the following:

* `performance.now()`
* `performance.getEntries()`
* `performance.getEntries()`
* `performance.getEntries()`
* `performance.mark()`
* `performance.measure()`
* `performance.clearMarks()`
* `performance.clearMeasures()`

It is not possible to polyfill `performance.timing.responseStart`, since that is information that is not available to JavaScript if the browser doesn't support it.
