### ISSUE TITLE
getEntries function is not working in Safari 10.0.3

### ISSUE THREAD

**Issue by NoelBroda** [nicjansma/usertiming.js#16]
Hi man!
I'm trying to use `window.performance.getEntries()` in Safari 10.0.3 and the functions always return an empty array.

**Comment by nicjansma** [comment]
Hi @NoelBroda!

I just opened the [usertiming.js test suite](https://github.com/nicjansma/usertiming.js/blob/master/test/test.html) in Safari 10.0.3 on Mac OS Sierra 10.12.3, and everything passed fine.

I also ran this, and got an entry back:

```
window.performance.mark("hi");
window.performance.getEntries(); // returns a single item
```

Can you share more with a test page?

**Comment by NoelBroda** [comment]
Oh! Sorry @nicjansma.
I just realized that what I need is the browser using the `window.performance.mark` function.

Meaning. If you call `window.performance.getEntries('resource')` in Chrome, you'll get all resources loaded by the browser (basically: what you see in the Network console in developers tools).

If I call the `mark` function, it works. But I need to browser calling it, and Safari is the only one where this behavior doesn't work.

**Comment by nicjansma** [comment]
@NoelBroda Please be aware that there's a difference between [UserTiming](https://www.w3.org/TR/user-timing/), where you can "mark" your own timestamps in the Performance Timeline (using `.getEntries()`) and [ResourceTiming](https://www.w3.org/TR/resource-timing/) which logs all resources fetched from the page (what you see in the Network tab in browser developer tools).

This polyfill only adds support UserTiming.  With it, you can `.mark()` and `.measure()` your own custom timestamps and durations.  It polyfills the Performance Timeline, so you can get those marks/measures later with `.getEntries()`.  It will not automatically log networking events.

There is no way to polyfill ResourceTiming -- either the browser supports it, or it doesn't, and you can't get the same information otherwise.

Unfortunately Safari [does not support ResourceTiming](http://caniuse.com/#feat=resource-timing) yet, so we'll just need to wait for them to support it.
